### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by Eevee-chan**

### CODE REVIEW

**Comment by gosha20777** [comment]
Wow! Thank you very much for contributing to our community!

@2326wz was writeing this project, not me. I'll ask him about your PR :-)

P.s. I think that `qty` means `quantity`.

**Comment by Eevee-chan** [comment]
You're welcome :)

**Comment by 2326wx** [comment]
> What "for another domain" means in this context? For other purposes? To train in other fields? Could you give an example?

E.g. for wildlife photos

**Comment by 2326wx** [comment]
> What `qty` here stands for? Quantity?

Exactly ))

**Comment by 2326wx** [comment]
> Wow! Thank you very much for contributing to our community!
> 
> @2326wz was writeing this project, not me. I'll ask him about your PR :-)
> 
> P.s. I think that `qty` means `quantity`.

I will check a bit later but looks good ))

**Pull request merged**
